export const productsInfo = [
  {
    id: "a",
    img: "/img/img1.jpg",
    title: "title 12 asdfasfasdfasfsd asf as sad fsa fasdf asdfasfd",
    qty: 1,
    description:
      "Description 1 lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon ",
    isFavorite: false,
    isCart: false,
    rate: 2,
    sales: 12,
    tag: 0,
    price: 4.99,
    discount: 0,
  },
  {
    id: "b",
    img: "/img/img2.jpg",
    title: "title 11",
    qty: 1,
    description:
      "Description 2 lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon ",
    isFavorite: true,
    isCart: false,
    rate: 3,
    sales: 15,
    tag: 1,
    price: 6.99,
    discount: 16,
  },
  {
    id: "c",
    img: "/img/img3.jpg",
    title: "title 10",
    qty: 1,
    description:
      "Description 3 lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon ",
    isFavorite: true,
    isCart: false,
    rate: 3,
    sales: 15,
    tag: 0,
    price: 6.99,
    discount: 16,
  },
  {
    id: "d",
    img: "/img/img4.jpg",
    title: "title 1",
    qty: 1,
    description:
      "Description 4 lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon ",
    isFavorite: true,
    isCart: false,
    rate: 4,
    sales: 20,
    tag: 0,
    price: 7.99,
    discount: 12,
  },
  {
    id: "e",
    img: "/img/img5.jpg",
    title: "title 2",
    qty: 1,
    description: "Description 5  ",
    isFavorite: true,
    isCart: true,
    rate: 5,
    sales: 600,
    tag: 1,
    price: 12.99,
    discount: 10,
  },
  {
    id: "f",
    img: "/img/img6.jpg",
    title: "title 3",
    qty: 1,
    description:
      "Description 6 lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon ",
    isFavorite: false,
    isCart: true,
    rate: 1,
    sales: 500,
    tag: 0,
    price: 22.99,
    discount: 19,
  },
  {
    id: "g",
    img: "/img/img2.jpg",
    title: "title 4",
    qty: 1,
    description:
      "Description 7 lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon ",
    isFavorite: true,
    isCart: false,
    rate: 5,
    sales: 15,
    tag: 1,
    price: 1.99,
    discount: 15,
  },
  {
    id: "h",
    img: "/img/img3.jpg",
    title: "title 5",
    qty: 1,
    description:
      "Description 8 lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon lorem ipsulon ",
    isFavorite: true,
    isCart: true,
    rate: 1,
    sales: 44,
    tag: 1,
    price: 1.99,
    discount: 15,
  },
];
