name: ecommerce-react
on:
  push:
    branches:
      - develop
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies and run build
        run: |
          npm ci
          npm run build
      - name: Configure credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::248189941884:role/full_access
          aws-region: us-east-1
      - name: Enviar para o S3
        run: |
          aws s3 sync ./dist s3://rhorauti-ecommerce-react --delete --cache-control "max-age=3600"
